name: C/C++ CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

    - name: Run program (optional)
      run: |
        ./readdir # Optional: if you want to run the compiled program as part of the workflow
